### ISSUE TITLE
Dependency problem with Clojure 1.8.0 

### ISSUE THREAD

**Issue by sammikko** [michaelklishin/welle#39]
My project dependencies are:
```
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [com.novemberain/welle "3.0.0"]]
```
(require '[clojurewerkz.welle.solr]) results in the following error: 

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:123)
Caused by: java.lang.NoClassDefFoundError: IllegalName: compile__stub.clj_http.headers.clj-http.headers/HeaderMap, compiling:(clj_http/headers.clj:105:1)
```

**Comment by michaelklishin** [comment]
Sorry but you have provided no evidence that this is somehow a problem with Welle.

Libraries cannot be blamed for dependency problems. You can exclude transient dependencies in `project.clj` using the `:exclude` option and inspect dependency tree using `lein deps :tree`.

You cannot claim that a problem with your project is that of Welle. And if you take a look at the stack trace — which I have pointed out to you before in #38 — you will discover that the library that cannot load is `clj-http`:

```
compile__stub.clj_http.headers.clj-http.headers/HeaderMap, compiling:(clj_http/headers.clj:105:1)
```

even then, the problem isn't necessarily with `clj-http`, it could be just that Welle depends on an old version of `clj-http` that was compiled for a specific JDK and/or Clojure version (although Clojure code is typically compiled when loaded).

Please start with inspecting all `clj-http` versions you have in `lein deps :tree`. And no, I am not available to explain how to detect conflicting dependencies and debug dependency issues: Clojure has a mailing list.

**Comment by michaelklishin** [comment]
Welle indeed depends on an old `clj-http` version but should work with newer versions just fine (clj-http API has been quite stable in the last few years). So using a Leiningen exclude for Welle is likely what you are after.
